# Copyright © 2021 Mark Dumay. All rights reserved.
# Use of this source code is governed by The MIT License (MIT) that can be found in the LICENSE file.

secrets:
  dns_cloudflare_api_token:
    file: secrets/dns_cloudflare_api_token.dev
    external: false

services:
  certbot:
    build:
      dockerfile: ./config/certbot/Dockerfile
      context: .
      args:
        BUILD_VERSION: "${BUILD_VERSION}"
        BUILD_UID: "${BUILD_UID}"
        BUILD_GID: "${BUILD_GID}"
        BUILD_FLAGS: --add-shell
        BUILD_TARGET: test
        CERTBOT_DNS_PLUGIN: "${CERTBOT_DNS_PLUGIN}"
        CERTBOT_VERSION: "${CERTBOT_VERSION}"

  nginx:
    build:
      dockerfile: ./config/nginx/Dockerfile
      context: .
      args:
        BUILD_VERSION: "${BUILD_VERSION}"
        BUILD_UID: "${BUILD_UID}"
        BUILD_GID: "${BUILD_GID}"
        BUILD_FLAGS: --add-shell -k nginx-debug
        BUILD_TARGET: test
        NGINX_VERSION: "${NGINX_VERSION}"