# Copyright © 2021 Mark Dumay. All rights reserved.
# Use of this source code is governed by The MIT License (MIT) that can be found in the LICENSE file.

services:
  certbot:
    build:
      dockerfile: ./config/certbot/Dockerfile
      context: .
      args:
        BUILD_VERSION: "${BUILD_VERSION}"
        BUILD_UID: "${BUILD_UID}"
        BUILD_GID: "${BUILD_GID}"
        BUILD_FLAGS: --add-shell --read-only
        BUILD_TARGET: production
        CERTBOT_DNS_PLUGIN: "${CERTBOT_DNS_PLUGIN}"
        CERTBOT_VERSION: "${CERTBOT_VERSION}"
    read_only: true
    volumes:
      - type: tmpfs
        target: /home/certbot
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /var/lib/certbot
      - type: tmpfs
        target: /var/log/certbot
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: "${CERTBOT_LIMIT_CPU}"
          memory: "${CERTBOT_LIMIT_MEM}"
        reservations:
          cpus: "${CERTBOT_RESERVATION_CPU}"
          memory: "${CERTBOT_RESERVATION_MEM}"

  nginx:
    build:
      dockerfile: ./config/nginx/Dockerfile
      context: .
      args:
        BUILD_VERSION: "${BUILD_VERSION}"
        BUILD_UID: "${BUILD_UID}"
        BUILD_GID: "${BUILD_GID}"
        BUILD_FLAGS: --add-shell --read-only
        BUILD_TARGET: production
        NGINX_VERSION: "${NGINX_VERSION}"
    read_only: true
    volumes:
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /var/lib/nginx/conf.d
      - type: tmpfs
        target: /var/cache/nginx
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: "${NGINX_LIMIT_CPU}"
          memory: "${NGINX_LIMIT_MEM}"
        reservations:
          cpus: "${NGINX_RESERVATION_CPU}"
          memory: "${NGINX_RESERVATION_MEM}"