version: "3.7"

secrets:
    dns_cloudflare_api_token:
        external: true

networks:
    certbot:
    portal:

volumes:
    certs:
    templates:

services:
    certbot:
        image: markdumay/certbot-${CERTBOT_DNS_PLUGIN}:latest
        restart: unless-stopped
        networks:
            - certbot
        volumes:
            - certs:/etc/certbot
        environment:
            - CERTBOT_DNS_PLUGIN=${CERTBOT_DNS_PLUGIN}
            - CERTBOT_DNS_PROPAGATION_SECONDS=${CERTBOT_DNS_PROPAGATION_SECONDS}
            - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
            - CERTBOT_EMAIL=${CERTBOT_EMAIL}
            - CERTBOT_DEPLOYMENT=${CERTBOT_DEPLOYMENT}
        secrets:
            - dns_cloudflare_api_token

    nginx:
        image: markdumay/nginx-unprivileged:latest
        ports:
            - ${HOST_PORT_HTTP}:8080
            - ${HOST_PORT_HTTPS}:4430
        networks:
            - portal
        volumes:
            - certs:/etc/certbot:ro
            - templates:/etc/nginx/templates
        environment:
            - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
            - NGINX_PORT_HTTP=${NGINX_PORT_HTTP}
            - NGINX_PORT_HTTPS=${NGINX_PORT_HTTPS}
            - NGINX_POLLING_INTERVAL=${NGINX_POLLING_INTERVAL}