# Copyright © 2021 Mark Dumay. All rights reserved.
# Use of this source code is governed by The MIT License (MIT) that can be found in the LICENSE file.

secrets:
  dns_cloudflare_api_token:
    file: secrets/dns_cloudflare_api_token.dev
    external: false

services:
  certbot:
    build:
      args:
        BUILD_FLAGS: --add-shell

  nginx:
    build:
      args:
        BUILD_FLAGS: --add-shell -k nginx-debug