# Copyright © 2021 Mark Dumay. All rights reserved.
# Use of this source code is governed by The MIT License (MIT) that can be found in the LICENSE file.

services:
  certbot:
    build:
      dockerfile: ./config/certbot/Dockerfile
      context: .
      args:
          BUILD_VERSION: "${BUILD_VERSION}"
          UID: "${UID}"
          GID: "${GID}"
          CERTBOT_DNS_PLUGIN: "${CERTBOT_DNS_PLUGIN}"
          BUILD_FLAG: --add-shell

  nginx:
    build:
      dockerfile: ./config/nginx/Dockerfile
      context: .
      args:
          BUILD_VERSION: "${BUILD_VERSION}"
          UID: "${UID}"
          GID: "${GID}"
          BUILD_FLAG: --add-shell