# Copyright © 2021 Mark Dumay. All rights reserved.
# Use of this source code is governed by The MIT License (MIT) that can be found in the LICENSE file.

version: "3.7"

secrets:
  dns_cloudflare_api_token:
    external: true

networks:
  certbot:
    driver_opts:
      encrypted: ""
  portal:
    driver_opts:
      encrypted: ""

volumes:
  certs:
  templates:

services:
  certbot:
    image: "markdumay/certbot-${CERTBOT_DNS_PLUGIN}:${BUILD_VERSION:?version}${IMAGE_SUFFIX:-}"
    restart: unless-stopped
    networks:
      - certbot
    volumes:
      - certs:/etc/certbot
    environment:
      - CERTBOT_DNS_PLUGIN=${CERTBOT_DNS_PLUGIN}
      - CERTBOT_DNS_PROPAGATION=${CERTBOT_DNS_PROPAGATION}
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_DEPLOYMENT=${CERTBOT_DEPLOYMENT}
    secrets:
      - source: dns_cloudflare_api_token
        target: dns_cloudflare_api_token
        uid: "${UID}"
        gid: "${GID}"
        mode: 0440 # TODO: check correct secret mode
    healthcheck:
      test: ["CMD", "certbot_issue.sh", "verify"]
      interval: 5m
      timeout: 10s
      retries: 3

  nginx:
    image: "markdumay/nginx-unprivileged:${BUILD_VERSION:?version}${IMAGE_SUFFIX:-}"
    restart: unless-stopped
    ports:
      - ${HOST_PORT_HTTP}:8080
      - ${HOST_PORT_HTTPS}:4430
    networks:
      - portal
    volumes:
      - certs:/etc/certbot:ro
      - templates:/etc/nginx/templates
    environment:
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
      - NGINX_PORT_HTTP=${NGINX_PORT_HTTP}
      - NGINX_PORT_HTTPS=${NGINX_PORT_HTTPS}
      - NGINX_POLLING_INTERVAL=${NGINX_POLLING_INTERVAL}
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:${NGINX_PORT_HTTP}"]
      interval: 1m30s
      timeout: 10s
      retries: 3